"""empty message

Revision ID: 003583be9620
Revises: 39ac89f566b2
Create Date: 2024-03-28 12:26:21.098301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003583be9620'
down_revision = '39ac89f566b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assitance')
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    op.create_table('assitance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='assitance_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='assitance_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assitance_pkey')
    )
    op.drop_table('assistance')
    # ### end Alembic commands ###
