"""empty message

Revision ID: 1e34f9f4ff82
Revises: eec9bf31eea3
Create Date: 2024-03-28 12:19:40.494525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e34f9f4ff82'
down_revision = 'eec9bf31eea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('banner_picture', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('social_networks', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('social_networks')
        batch_op.drop_column('banner_picture')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('city')
        batch_op.drop_column('gender')
        batch_op.drop_column('description')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
