"""empty message

Revision ID: 2ec9b4901cef
Revises: d4dc9d37d415
Create Date: 2024-04-21 21:31:22.238402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec9b4901cef'
down_revision = 'd4dc9d37d415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_band_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['created_band_id'])
        batch_op.create_foreign_key(None, 'band', ['created_band_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_band_id')

    # ### end Alembic commands ###
