"""empty message

<<<<<<<< HEAD:migrations/versions/9035a327ea44_.py
Revision ID: 9035a327ea44
Revises: 71c4f16ca424
Create Date: 2024-04-21 20:31:38.611677
========
Revision ID: 3c732d86f79c
Revises: f6907425c4e3
Create Date: 2024-04-21 20:16:20.835618
>>>>>>>> cambios-heyson-2:migrations/versions/3c732d86f79c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/9035a327ea44_.py
revision = '9035a327ea44'
down_revision = '71c4f16ca424'
========
revision = '3c732d86f79c'
down_revision = 'f6907425c4e3'
>>>>>>>> cambios-heyson-2:migrations/versions/3c732d86f79c_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_band_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['created_band_id'])
        batch_op.create_foreign_key(None, 'band', ['created_band_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_band_id')

    # ### end Alembic commands ###
