"""empty message

Revision ID: 56f5296ea673
Revises: 003583be9620
Create Date: 2024-03-28 12:34:55.125275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f5296ea673'
down_revision = '003583be9620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.drop_column('place')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
